using UnityEngine;

public class LifeController : MonoBehaviour
{
    public Animator animator;
    private Vector3 respawnPosition;
    
    private int deathCount = 0;
    private void Start()
    {
        MapMaker mapMaker = FindObjectOfType<MapMaker>();
        if (mapMaker != null)
        {
            respawnPosition = MapMaker.startCubePosition + Vector3.up * 10f;
        }
        else
        {
            Debug.LogError("mapMaker not found in scene!");
        }
    }
    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Finish"))
        {
            deathCount++;
            UIManager.Instance.DecreaseLife();

            if (deathCount >= 3)
            {
                animator.SetTrigger("DieTrigger");
                UIManager.Instance.ShowGameOverPanel();
                Debug.Log(" 플레이어 사망 횟수 초과! Game Over 처리");
                
            }
            else
            {
                RespawnPlayer();
            }
        }
    }
    private void RespawnPlayer()
    {
        CharacterController cc = GetComponent<CharacterController>();
        if (cc != null)
        {
            cc.enabled = false;
            transform.position = respawnPosition;
            cc.enabled = true;
        }
        else
        {
            transform.position = respawnPosition;
        }

        animator.SetTrigger("IntroTrigger");
        Invoke(nameof(ResetToIdle), 1.0f); // 1초 후 Idle 트리거 

        Debug.Log("[LifeController] 플레이어 리스폰 완료!");
    }

    private void ResetToIdle()
    {
        animator.SetTrigger("IdleTrigger");
    }
    
}